import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { chivo, readexPro } from "./fonts";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${readexPro.className} ${chivo.className} relative bg-white`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
